export const UPDATE_TITLE = 'UPDATE_TITLE';
export const ADD_QUESTION = 'ADD_QUESTION';
export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';

export const INIT_ANSWERS = 'INIT_ANSWERS';
export const UPDATE_ANSWER = 'UPDATE_ANSWER';
export const CLEAR_ANSWERS = 'CLEAR_ANSWERS';
